/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 2
#
# Initialize kernel
/run/initialize

/gps/energy 0. MeV
/gps/pos/confine PENShell

/gps/particle ion
/gps/ion 89 228 0 0
/run/beamOn 100

/gps/particle ion
/gps/ion 90 232 0 0
/run/beamOn 100

/gps/particle ion
/gps/ion 19 40 0 0
/run/beamOn 100